"""Unit tests for the completion command."""

from unittest.mock import MagicMock

from workspace_cli.cli import build_parser
from workspace_cli.commands.completion import handle_completion, register_command


class TestRegisterCommand:
    """Tests for register_command."""

    def test_creates_completion_subparser(self):
        """register_command adds a 'completion' subparser."""
        mock_subparsers = MagicMock()
        mock_parser = MagicMock()
        mock_subparsers.add_parser.return_value = mock_parser

        register_command(mock_subparsers, parent_parser=MagicMock())

        mock_subparsers.add_parser.assert_called_once_with(
            "completion",
            help="Generate shell completion script",
        )

    def test_adds_shell_argument_with_choices(self):
        """register_command adds a 'shell' positional argument with bash/zsh choices."""
        mock_subparsers = MagicMock()
        mock_parser = MagicMock()
        mock_subparsers.add_parser.return_value = mock_parser

        register_command(mock_subparsers, parent_parser=MagicMock())

        mock_parser.add_argument.assert_called_once_with(
            "shell",
            choices=["bash", "zsh"],
            help="Shell to generate completions for",
        )

    def test_stores_parent_parser_in_defaults(self):
        """register_command stores the parent parser in defaults."""
        mock_subparsers = MagicMock()
        mock_parser = MagicMock()
        mock_subparsers.add_parser.return_value = mock_parser
        parent = MagicMock()

        register_command(mock_subparsers, parent_parser=parent)

        mock_parser.set_defaults.assert_called_once()
        call_kwargs = mock_parser.set_defaults.call_args[1]
        assert call_kwargs["_parent_parser"] is parent
        assert call_kwargs["func"] is handle_completion


class TestHandleCompletion:
    """Tests for handle_completion."""

    def test_bash_output_contains_expected_markers(self, capsys):
        """Bash completion output contains shtab header and subcommand list."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "AUTOMATICALLY GENERATED by `shtab`" in output
        assert "catalog" in output
        assert "code" in output
        assert "completion" in output
        assert "template" in output
        assert "setup-devcontainer" in output

    def test_zsh_output_contains_expected_markers(self, capsys):
        """Zsh completion output contains compdef header and subcommand list."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "zsh"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "#compdef" in output
        assert "AUTOMATICALLY GENERATED by `shtab`" in output
        assert "catalog" in output
        assert "template" in output

    def test_bash_output_includes_option_strings(self, capsys):
        """Bash completion output includes CLI flags."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "--skip-update-check" in output
        assert "--ide" in output
        assert "--catalog-url" in output
        assert "--tags" in output

    def test_bash_output_includes_template_subcommands(self, capsys):
        """Bash completion output includes template subcommands."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "save" in output
        assert "load" in output
        assert "view" in output
        assert "edit" in output
        assert "delete" in output
        assert "create" in output
        assert "upgrade" in output

    def test_bash_output_includes_catalog_subcommands(self, capsys):
        """Bash completion output includes catalog subcommands."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "'list'" in output
        assert "'validate'" in output


class TestBuildParser:
    """Tests for build_parser."""

    def test_returns_parser_with_subcommands(self):
        """build_parser returns a parser with all expected subcommands."""
        parser = build_parser()
        # Parse a known subcommand to verify it's registered
        args = parser.parse_args(["completion", "bash"])
        assert args.command == "completion"
        assert args.shell == "bash"

    def test_parser_has_all_commands(self):
        """build_parser registers all expected command subparsers."""
        parser = build_parser()

        # Verify each command is parseable
        for cmd in ["completion bash", "template list", "catalog list"]:
            args = parser.parse_args(cmd.split())
            assert args.command == cmd.split()[0]

    def test_completion_has_parent_parser_default(self):
        """build_parser stores parent parser in completion defaults."""
        parser = build_parser()
        args = parser.parse_args(["completion", "bash"])
        assert args._parent_parser is parser


class TestPreamble:
    """Tests for dynamic template name completion preamble."""

    def test_bash_preamble_contains_template_names_function(self, capsys):
        """Bash output includes _workspace_template_names shell function."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "_workspace_template_names()" in output
        assert "workspace-templates" in output

    def test_zsh_preamble_contains_template_names_function(self, capsys):
        """Zsh output includes _workspace_template_names shell function."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "zsh"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "_workspace_template_names()" in output
        assert "workspace-templates" in output

    def test_bash_links_template_completer_to_view_edit_load_delete_upgrade(self, capsys):
        """Bash output references _workspace_template_names for template subcommands."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        for subcmd in ["view", "edit", "load", "delete", "upgrade"]:
            assert f"template_{subcmd}_pos_0_COMPGEN=_workspace_template_names" in output

    def test_bash_does_not_link_completer_to_save_and_create(self, capsys):
        """Bash output does NOT reference _workspace_template_names for save/create."""
        parser = build_parser()
        args = MagicMock()
        args.shell = "bash"
        args._parent_parser = parser

        handle_completion(args)

        output = capsys.readouterr().out
        assert "template_save_pos_0_COMPGEN=_workspace_template_names" not in output
        assert "template_create_pos_0_COMPGEN=_workspace_template_names" not in output
